export const CARD_SETTING = {
  WIDTH: 1161,
  HEIGHT: 591.729,
  PADDING: {
    LEFT: 63,
    RIGHT: 63,
    TOP: 50,
    BOTTOM: 50,
  },
};

export const PADDING_X = `pl-[${CARD_SETTING.PADDING.LEFT}px] pr-[${CARD_SETTING.PADDING.RIGHT}px]`;

export const TEXT_EDITOR_BUBBLE_LEFT = CARD_SETTING.PADDING.LEFT / 1.5;
